import type { Metadata } from "next";
import '../styles/reset.css';
import "./globals.css";
import Header from "@/components/Functional/Header/Header";
import Footer from "@/components/Functional/Footer/Footer";
import { ModalProvider } from "@/store/Modal.context";
import { AuthProvider } from "@/store/User.context";

export const metadata: Metadata = {
  title: "Elegance Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="">
        <ModalProvider>
        <AuthProvider>
        <Header />
        <main className="min-h-screen bg-main w-full">
        {children}
        </main>
        <Footer />
        </AuthProvider>
        </ModalProvider>
      </body>
    </html>
  );
}
