import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Functional/Header/Header";
import Footer from "@/components/Functional/Footer/Footer";
import { ModalProvider } from "@/store/Modal.context";

export const metadata: Metadata = {
  title: "Elegance Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <ModalProvider>
        <Header />
        <main className="min-h-screen bg-main">
        {children}
        </main>
        <Footer />
        </ModalProvider>
      </body>
    </html>
  );
}
